[package]
name = "arena"
version = "0.1.0"
authors = ["dyens <dyens@mail.ru>"]

[profile.dev]
debug = true
opt-level = 0

[dependencies]
argparse = "*"
image = "*"
chrono = "*"
piston_window = "*"
piston2d-graphics = "*"
find_folder = "*"
gfx_device_gl = "*"
nalgebra = "*"
ncollide = "*"
